[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "shell lgit --block"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "f" ]
run  = 'shell "lgit --filter %h" --block'
desc = "run lazygit"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin wide-preview"
desc = "Toggle wide preview pane (1:1:6 vs 1:3:4)"

